name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2

    - run: cargo test --all

  lint:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: --deny warnings

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2

    - run: cargo update --locked --package cargo-path

    - run: cargo clippy --all

    - run: cargo fmt --all -- --check

    - run: |
        sudo apt-get update
        sudo apt-get install ripgrep
        ./bin/forbid
